name: change project name

# Controls when the action will run.
env:
  APP_NAME: abdulvhora
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rename-project-name:
    name: change project name
    runs-on: ubuntu-latest
    steps:
 
      - name: start renaming project
        run: echo start work 
        
      - name: start renaming project
        run: echo "$APP_NAME"
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Generate signed APK
        run: cd android && ./gradlew app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: pick-store-app.apk
          path: android/app/build/outputs/apk/release/"$APP_NAME".apk
