


name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Create local changes
      run: |
        ...
    - name: Commit files
      run: |
        git config --local user.email "abdulrauf_vhora@codenticsoftware.com"
        git config --local user.name "abdul"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: Abdulrauf-vhora/demo-CI-CD@main
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
