name: change project name

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rename-project-name:
    name: change project name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: start renaming project
        run: npx react-native-rename demoApp -b com.demoApp
