name: Generate release APK
env:
  PROJECT_NAME: Monday

  
# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    env:
      APP_NAME: /Users/CS012/Abdul/ReactNative/Practice/AwesomeProject
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2
      - name: GitHub Script
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('/Users/CS012/Abdul/Script/rename.sh')
            console.log(script({github, context}))

  
      # - name: Install npm dependencies
      #   run: npm install --legacy-peer-deps

      # - name: Generate signed APK
      #   run: cd android && ./gradlew app:assembleRelease

      # - name: Upload release APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: pick-store-app.apk
      #     path: android/app/build/outputs/apk/release/app-release.apk
