name: change project name

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rename-project-name:
    name: change project name
    runs-on: ubuntu-latest
    steps:
 
      - name: start renaming project
        run: echo Abdul 
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
