
name: Generate release APK
env:
  APP_NAME: abdulvhora
# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Generate signed APK
        run: cd android && ./gradlew app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: pick-store-app.apk
          path: android/app/build/outputs/apk/release/"$APP_NAME".apk
