name: change project name

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rename-project-name:
    name: change project name
    runs-on: ubuntu-latest
    steps:
      - name: start renaming project
        run: npx react-native-rename demoApp -b com.demoApp
      
    - name: Commit files
      run: |
        git commit -m "Add changes" -a
    - name: Push changes
      uses: Abdulrauf-vhora/demo-CI-CD@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  
